######################################################################################################
## Travis-CI control file                                                                           ##
##                                                                                                  ##
## Date       Developer           Comments                                                          ##
## ========== =================== ================================================================= ##
## 2020-09-28 SV-Zanshin          Issue #14, added clang-format checking                            ##
## 2020-05-11 SV-Zanshin          Removed uneeded install libraries                                 ##
## 2019-02-02 SV-Zanshin          Uncommented doxygen callorrected PRETTYNAME                       ##
## 2019-01-27 SV-Zanshin          Corrected PRETTYNAME                                              ##
## 2019-01-20 SV-Zanshin          Linked to Adafruit script rather than manually defining all tests ##
## 2019-01-19 SV-Zanshin          Initial coding                                                    ##
##                                                                                                  ##
######################################################################################################
language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages
    
git:
  depth: false
  quiet: true
  addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - python3-pip
      - python3-wheel
      - clang-format-5.0

env:
  global:
    - PRETTYNAME="SV-Zanshin Maxim Integrated DS3231M I2C Thermometer Arduino Library"
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
  - curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/run-clang-format.py > run-clang-format.py

install:

script:
  - build_main_platforms

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
